Define main_exec()
Signed-off-by: Abhishek Chakravarti <abhishek@taranjali.org>

diff --git a/tools/provision b/tools/provision
--- a/tools/provision
+++ b/tools/provision
@@ -6,4 +6,75 @@
 . "$(dirname "0")/../ext/ru.sh/src/pkg.sh"
 
 
+# Log file where messages are stored.
+
 LOG_FILE=provision.log
+
+
+# Sets up command line flags; we use long options in order to be more explicit.
+# --target is the target environment to provision, and --reset rebuilds the
+# target environment if it already exists. As of now we only support Vagrant
+# environments.
+
+main_flags()
+{
+        DEFINE_string 'target' 'vagrant/arch' 'target environment' 1001
+        DEFINE_boolean 'reset' false 'rebuild platform' 1002
+
+        FLAGS "$@" || exit $?
+        eval set -- "$FLAGS_ARGV"
+}
+
+
+# Performs actual provisioning steps. Since we only support Vagrant environments
+# as of now, we start off by checking that the vagrant executable is available.
+# Subsequently, one of the following execution paths is taken
+#   - If no Vagrantfile is found, we build and boot the Vagrant box
+#   - If a Vagrantfile is found and --reset is specified, we rebuild the box
+#   - If a Vagrantfile exist and --reset is not specified, we run the box
+
+main_exec()
+{
+        if vagrant -v >/dev/null 2>&1
+        then
+                log_ok "vagrant command found"
+        else
+                log_fail  "vagrant command not found"
+        fi
+
+        if ! [ -e Vagrantfile ]
+        then
+                vg_build
+                vg_boot
+
+        else
+                log_ok "existing Vagrantfile found"
+
+                if [ "$FLAGS_reset" = "$FLAGS_TRUE" ]
+                then
+                        log_warn "--reset set, removing existing Vagrant box"
+
+                        vagrant halt >/dev/null 2>&1
+                        vagrant destroy -f >/dev/null 2>&1
+                        rm Vagrantfile
+
+                        log_ok "removed existing Vagrant box"
+
+                        vg_build
+                        vg_boot
+
+                elif vagrant status | grep "is running" >/dev/null 2>&1
+                then
+                        log_ok "Vagrant box already running, skipping"
+
+                else
+                        vg_boot
+                fi
+        fi
+}
+
+
+# Parse command line flags and execute script.
+
+main_flags "$@"
+main_exec
